project:
  type: website
  output-dir: docs
  
website:
  title: "精通Excel数据统计与分析"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 第1篇.qmd
      - 第2篇.qmd
      - 第3篇.qmd
      - 第4篇.qmd
      - 第5篇.qmd
    tools:
      - icon: envelope
        href: lizongzhang9@qq.com
  page-footer:
    right: "Data illuminates insights."
    left: "&copy; Copyright 2024, Li Zongzhang"
format:
  html:
    theme: cerulean
    fontcolor: "#044875"
    toc: true
editor: source

